### ISSUE TITLE
Testing React-Capacitor App with Jest getting me wasm file error

### ISSUE THREAD

**Issue by Brandi-Youreka** [jepiqueau/jeep-sqlite#24]
Hi y'all 👋 I use this library via the capacitor-community/sqlite library within my application. I am hoping to write some unit tests with Jest where each test has a db instance that I can seed and use to test. I've ran into an issue implementing this db instance in my test file where jeep-sqlite cannot load the specified wasm file. Here is my test file I am trying to implement

```ts
import { resolve } from 'path';
import { CapacitorSQLite, SQLiteConnection, SQLiteDBConnection } from '@capacitor-community/sqlite';
import { defineCustomElements as jeepSqlite, applyPolyfills, JSX as LocalJSX  } from 'jeep-sqlite/loader';
// ...

const dbName = config.databaseName;

type StencilToReact<T> = {
    [P in keyof T]?: T[P] & Omit<HTMLAttributes<Element>, 'className'> & {
        class?: string;
    };
} ;

declare global {
    export namespace JSX {
        interface IntrinsicElements extends StencilToReact<LocalJSX.IntrinsicElements> {
        }
    }
}

applyPolyfills().then(() => {
    jeepSqlite(window, {});
});

it('test', async () => {
  const sqlite: SQLiteConnection = new SQLiteConnection(CapacitorSQLite);

  const jeepEl = document.createElement('jeep-sqlite');
  document.body.appendChild(jeepEl);
  const element = await customElements.whenDefined('jeep-sqlite');
  
  const assetPath = resolve(`${__dirname}/../../../public/assets`); // we've also tried '.../assets/sql-wasm.wasm'
  jeepEl.setAttribute('wasmPath', assetPath ); // attempt to set the wasmPath
  
  const sqlite: SQLiteConnection = new SQLiteConnection(CapacitorSQLite);
  await sqlite.initWebStore();
  
  const ret = await sqlite.checkConnectionsConsistency();
  const isConn = (await sqlite.isConnection(dbName, false)).result;
  let db: SQLiteDBConnection;
  if (ret.result && isConn) {
      db = await sqlite.retrieveConnection(dbName, false);
  } else {
      db = await sqlite.createConnection(dbName, false, 'no-encryption', 1, false);
  }
  try {
      await db.open();
  } catch (err) {
      // ...   
  }
  // ...
}

```

And we get the following errors:

```
console.error
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (<omitted>/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:63:19)
          at Request.<anonymous> (<omitted>/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
          at Request.emit (node:events:539:35)
          at ClientRequest.<anonymous> (<omitted>/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)
          at ClientRequest.emit (node:events:527:28)
          at Socket.socketErrorListener (node:_http_client:454:9)
          at Socket.emit (node:events:527:28)
          at emitErrorNT (node:internal/streams/destroy:157:8)
          at emitErrorCloseNT (node:internal/streams/destroy:122:3)
          at processTicksAndRejections (node:internal/process/task_queues:83:21) undefined

      at VirtualConsole.<anonymous> (node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)

    console.warn
      Aborted(both async and sync fetching of the wasm failed)

      at E (node_modules/jeep-sqlite/dist/cjs/node_modules/sql.js/dist/sql-wasm.js:101:136)
      at ab (node_modules/jeep-sqlite/dist/cjs/node_modules/sql.js/dist/sql-wasm.js:102:149)
      at node_modules/jeep-sqlite/dist/cjs/node_modules/sql.js/dist/sql-wasm.js:103:256

    console.warn
      failed to asynchronously prepare wasm: RuntimeError: Aborted(both async and sync fetching of the wasm failed). Build with -sASSERTIONS for more info.

      at node_modules/jeep-sqlite/dist/cjs/node_modules/sql.js/dist/sql-wasm.js:158:377

    console.warn
      Aborted(RuntimeError: Aborted(both async and sync fetching of the wasm failed). Build with -sASSERTIONS for more info.)

      at E (node_modules/jeep-sqlite/dist/cjs/node_modules/sql.js/dist/sql-wasm.js:101:136)
      at node_modules/jeep-sqlite/dist/cjs/node_modules/sql.js/dist/sql-wasm.js:158:425

  ● getLookupRecordData › updateOfflineData › test db

    both async and sync fetching of the wasm failed

      at Object.Module.onAbort (node_modules/jeep-sqlite/dist/cjs/node_modules/sql.js/dist/sql-wasm.js:40:20)
      at E (node_modules/jeep-sqlite/dist/cjs/node_modules/sql.js/dist/sql-wasm.js:101:106)
      at ab (node_modules/jeep-sqlite/dist/cjs/node_modules/sql.js/dist/sql-wasm.js:102:149)
      at node_modules/jeep-sqlite/dist/cjs/node_modules/sql.js/dist/sql-wasm.js:103:256

  ● getLookupRecordData › updateOfflineData › test db

    RuntimeError: Aborted(RuntimeError: Aborted(both async and sync fetching of the wasm failed). Build with -sASSERTIONS for more info.). Build with -sASSERTIONS for more info.

      at E (node_modules/jeep-sqlite/dist/cjs/node_modules/sql.js/dist/sql-wasm.js:101:154)
      at node_modules/jeep-sqlite/dist/cjs/node_modules/sql.js/dist/sql-wasm.js:158:425
```

So I guess a two questions:

1. Is there anything that stands out as wrong above code?
2. Is there are preferred way to run jeep-sql lite in Jest (ie do we need mount the component within JSDom, or some other machanism?)
3. Are there any common gotchas when testing with jeep-sql?

Any hints would be highly appreciated! Thanks!

**Comment by Brandi-Youreka** [comment]
The solution that worked was spinning up a server before running the test. So we added the following scripts to our package.json:

```
  "scripts": {
    "serve": "cp node_modules/sql.js/dist/sql-wasm.wasm build/assets && serve -l 80 build/",
    "test": "{Your test script here}",
    "test:serve": "npm-run-all --parallel -r serve test", 
  },
```

Then we ran `npm run test:serve` when running the test. The `test:serve` script serves a local host that jeepSqlite is trying to reach out to in order to retrieve the sql-wasm.wasm file.
