### ISSUE TITLE
Error: No loader is configured for ".map" when update from ``v2.5.6`` to ``v2.5.9``

### ISSUE THREAD

**Issue by KiddoV** [jepiqueau/jeep-sqlite#36]
I got this error after updated package to ``v2.5.9``:

```terminal
>npm run dev

X [ERROR] No loader is configured for ".map" files: node_modules/jeep-sqlite/dist/esm/jeep-sqlite.entry.js.map

    node_modules/jeep-sqlite/dist/esm/index-42fe02e2.js:3981:4:
      3981 │     `./${bundleId}.entry.js${BUILD.hotModuleReplacement && hmrVersionId ? '?s-hmr=' + hmrVersionId : ''}`).then((importedModule) => {
           ╵     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

...\node_modules\esbuild\lib\main.js:1651
  let error = new Error(text);
              ^

Error: Build failed with 1 error:
node_modules/jeep-sqlite/dist/esm/index-42fe02e2.js:3981:4: ERROR: No loader is configured for ".map" files: node_modules/jeep-sqlite/dist/esm/jeep-sqlite.entry.js.map
    at failureErrorWithLog (...\node_modules\esbuild\lib\main.js:1651:15)
    at ...\node_modules\esbuild\lib\main.js:1059:25
    at ...\node_modules\esbuild\lib\main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v20.10.0
```

**Comment by jepiqueau** [comment]
@KiddoV use v2.5.10

**Comment by KiddoV** [comment]
Works, thanks!
