### ISSUE TITLE
Angular: Esbuild not working

### ISSUE THREAD

**Issue by paulstelzer** [jepiqueau/jeep-sqlite#42]
Jeep SQLite is not compatible with Angular ESbuild. If I change the build executor to "@angular-devkit/build-angular:browser-esbuild" or "@angular-devkit/build-angular:application", it is not working because he cannot resolve crypto.

```
✘ [ERROR] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-pre-bundle]

node_modules/esbuild/lib/main.js:1225:21:
1225 │         let result = await callback({
╵                      ^

at packageEntryFailure (file:///Users/paulstelzer/test/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:47164:15)
at resolvePackageEntry (file:///Users/paulstelzer/test/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:47161:3)
at tryNodeResolve (file:///Users/paulstelzer/test/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:46977:16)
at ResolveIdContext.resolveId (file:///Users/paulstelzer/test/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:46727:19)
at PluginContainer.resolveId (file:///Users/paulstelzer/test/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:49506:17)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async file:///Users/paulstelzer/test/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:66556:15
at async file:///Users/paulstelzer/test/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:47480:28
at async requestCallbacks.on-resolve (/Users/paulstelzer/test/node_modules/esbuild/lib/main.js:1225:22)
at async handleRequest (/Users/paulstelzer/test/node_modules/esbuild/lib/main.js:647:11)

This error came from the "onResolve" callback registered here:

node_modules/esbuild/lib/main.js:1150:20:
1150 │       let promise = setup({
╵                     ^

at setup (file:///Users/paulstelzer/test/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:47463:13)
at handlePlugins (/Users/paulstelzer/test/node_modules/esbuild/lib/main.js:1150:21)
at buildOrContextImpl (/Users/paulstelzer/test/node_modules/esbuild/lib/main.js:873:5)
at Object.buildOrContext (/Users/paulstelzer/test/node_modules/esbuild/lib/main.js:699:5)
at /Users/paulstelzer/test/node_modules/esbuild/lib/main.js:2032:68
at new Promise (<anonymous>)
at Object.context (/Users/paulstelzer/test/node_modules/esbuild/lib/main.js:2032:27)
at Object.context (/Users/paulstelzer/test/node_modules/esbuild/lib/main.js:1874:58)
at prepareEsbuildOptimizerRun (file:///Users/paulstelzer/test/node_modules/vite/dist/node/chunks/dep-C1-ZB6nQ.js:51405:33)

The plugin "vite:dep-pre-bundle" was triggered by this import

node_modules/jeep-sqlite/dist/esm/jeep-sqlite.entry.js:2924:28:
2924 │             var a = require("crypto");
╵                             ~~~~~~~~

/Users/paulstelzer/test/node_modules/esbuild/lib/main.js:1472
let error = new Error(text);
^

Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1225:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json.
at failureErrorWithLog (/Users/paulstelzer/test/node_modules/esbuild/lib/main.js:1472:15)
at /Users/paulstelzer/test/node_modules/esbuild/lib/main.js:945:25
at /Users/paulstelzer/test/node_modules/esbuild/lib/main.js:1353:9
at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
errors: [Getter/Setter],
warnings: [Getter/Setter]
}

Node.js v20.14.0
```

**Comment by paulstelzer** [comment]
My bad, solution has to been not here. If everyone else has the same issue, please take a look at https://github.com/angular/angular-cli/issues/26901
