### ISSUE TITLE
Error: Uncaught (in promise): TypeError: x is not a function

### ISSUE THREAD

**Issue by skjamil** [jepiqueau/jeep-sqlite#43]
I am getting the following error in console in ionic Application.
Error: Uncaught (in promise): TypeError: x is not a function
TypeError: x is not a function
    at x (jeep-sqlite.entry.js:2648:80)
    at f.onRuntimeInitialized (jeep-sqlite.entry.js:2555:318)
    at a (jeep-sqlite.entry.js:2649:432)
    at cd (jeep-sqlite.entry.js:2650:319)
    at bd (jeep-sqlite.entry.js:2648:419)
    at a (jeep-sqlite.entry.js:2641:286)
    at jeep-sqlite.entry.js:2642:21
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:11083:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at resolvePromise (zone.js:1193:31)
    at zone.js:1100:17
    at zone.js:1116:33
    at _ZoneDelegate.invoke (zone.js:368:26)
    at Object.onInvoke (core.mjs:11083:33)
    at _ZoneDelegate.invoke (zone.js:367:52)
    at Zone.run (zone.js:129:43)
    at zone.js:1257:36
    at _ZoneDelegate.invokeTask (zone.js:402:31)
    at core.mjs:10757:55
[package.json](https://github.com/user-attachments/files/16571606/package.json)

**Comment by jepiqueau** [comment]
@skjamil You must update the sql-wasm.wasm file in your assets forlder from node_modules/sql.js/dist/sql-wasm.wasm. I have added a note in the readme.md
